name: Auto Generate Sitemap

on:
  push:
    branches:
      - main  # или master, смотря какая ветка у вас главная
  workflow_dispatch: # Позволяет запускать генерацию вручную кнопкой

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Run sitemap generator
      run: python generate_sitemap.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sitemap.xml
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-updated sitemap.xml via GitHub Actions"
        git push
